GET http://localhost:5014/games

###
GET http://localhost:5014/games/4

###
POST http://localhost:5014/games
Content-Type: application/json

{
    "name": "Super Mario Bros",
    "genreId": 1,
    "price": 69.99,
    "releaseDate": "2023-10-20"
}

###
PUT http://localhost:5014/games/4
Content-Type: application/json

{
    "name": "Astro Bot",
    "genreId": 3,
    "price": 59.99,
    "releaseDate": "2025-08-05"
}

###
DELETE  http://localhost:5014/games/3

###
GET  http://localhost:5014/genres